### ISSUE TITLE
No binary releases

### ISSUE THREAD

**Issue by spkane** [minamijoyo/tflock#3]
It would be useful to have an official github release that contained a set of binaries already built and easy to install for endusers.

Using something like https://github.com/mitchellh/gox it is very easy to manage the build.

**Comment by minamijoyo** [comment]
Thank you for opening the issue.

I had written the tflock for refactoring Terraform configurations, but after using it, I figured out a more sophisticated way and I wrote a new tool: https://github.com/minamijoyo/tfmigrate

If your concern is only refactoring, I highly recommend you to use the tfmigrate rather than the tflock. Honestly, I'm not use the tflock for now. Does this project still have some meanings for you? If so, please let me know why. Thanks!

**Comment by spkane** [comment]
I have used this mostly for testing CI tolling in the past and how it handled locks, but I agree that their are likely better ways to handle it nowadays. Thank you for your work on this. It has been useful.
